# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c2966d42e86ccae75503b0e02958f75b4a98b0e1c27e6a3589fe5c8640313efca6c1c9631793b67c336190a472874244e32aa0b9e4973f2a0982ac04dd4750f

test:
  secret_key_base: 2cbc8f126e1be3077dac9c830f852e6f6a479ac27d7b55d81d4ce04c287464ff66650338dfc707d27197391cb05fe3474c20e675d55748455468248c534c5793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
